#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.0
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

[assembly: global::Android.Runtime.ResourceDesignerAttribute("SevenDays.UI.Droid.Resource", IsApplication=true)]

namespace SevenDays.UI.Droid
{
	
	
	[System.CodeDom.Compiler.GeneratedCodeAttribute("Xamarin.Android.Build.Tasks", "1.0.0.0")]
	public partial class Resource
	{
		
		static Resource()
		{
			global::Android.Runtime.ResourceIdManager.UpdateIdValues();
		}
		
		public static void UpdateIdValues()
		{
			global::Acr.UserDialogs.Resource.Attribute.ahBarColor = global::SevenDays.UI.Droid.Resource.Attribute.ahBarColor;
			global::Acr.UserDialogs.Resource.Attribute.ahBarLength = global::SevenDays.UI.Droid.Resource.Attribute.ahBarLength;
			global::Acr.UserDialogs.Resource.Attribute.ahBarWidth = global::SevenDays.UI.Droid.Resource.Attribute.ahBarWidth;
			global::Acr.UserDialogs.Resource.Attribute.ahCircleColor = global::SevenDays.UI.Droid.Resource.Attribute.ahCircleColor;
			global::Acr.UserDialogs.Resource.Attribute.ahDelayMillis = global::SevenDays.UI.Droid.Resource.Attribute.ahDelayMillis;
			global::Acr.UserDialogs.Resource.Attribute.ahRadius = global::SevenDays.UI.Droid.Resource.Attribute.ahRadius;
			global::Acr.UserDialogs.Resource.Attribute.ahRimColor = global::SevenDays.UI.Droid.Resource.Attribute.ahRimColor;
			global::Acr.UserDialogs.Resource.Attribute.ahRimWidth = global::SevenDays.UI.Droid.Resource.Attribute.ahRimWidth;
			global::Acr.UserDialogs.Resource.Attribute.ahSpinSpeed = global::SevenDays.UI.Droid.Resource.Attribute.ahSpinSpeed;
			global::Acr.UserDialogs.Resource.Attribute.ahText = global::SevenDays.UI.Droid.Resource.Attribute.ahText;
			global::Acr.UserDialogs.Resource.Attribute.ahTextColor = global::SevenDays.UI.Droid.Resource.Attribute.ahTextColor;
			global::Acr.UserDialogs.Resource.Attribute.ahTextSize = global::SevenDays.UI.Droid.Resource.Attribute.ahTextSize;
			global::Acr.UserDialogs.Resource.Drawable.ic_errorstatus = global::SevenDays.UI.Droid.Resource.Drawable.ic_errorstatus;
			global::Acr.UserDialogs.Resource.Drawable.ic_successstatus = global::SevenDays.UI.Droid.Resource.Drawable.ic_successstatus;
			global::Acr.UserDialogs.Resource.Drawable.roundedbg = global::SevenDays.UI.Droid.Resource.Drawable.roundedbg;
			global::Acr.UserDialogs.Resource.Drawable.roundedbgdark = global::SevenDays.UI.Droid.Resource.Drawable.roundedbgdark;
			global::Acr.UserDialogs.Resource.Id.loadingImage = global::SevenDays.UI.Droid.Resource.Id.loadingImage;
			global::Acr.UserDialogs.Resource.Id.loadingProgressBar = global::SevenDays.UI.Droid.Resource.Id.loadingProgressBar;
			global::Acr.UserDialogs.Resource.Id.loadingProgressWheel = global::SevenDays.UI.Droid.Resource.Id.loadingProgressWheel;
			global::Acr.UserDialogs.Resource.Id.textViewStatus = global::SevenDays.UI.Droid.Resource.Id.textViewStatus;
			global::Acr.UserDialogs.Resource.Layout.loading = global::SevenDays.UI.Droid.Resource.Layout.loading;
			global::Acr.UserDialogs.Resource.Layout.loadingimage = global::SevenDays.UI.Droid.Resource.Layout.loadingimage;
			global::Acr.UserDialogs.Resource.Layout.loadingprogress = global::SevenDays.UI.Droid.Resource.Layout.loadingprogress;
			global::Acr.UserDialogs.Resource.String.ApplicationName = global::SevenDays.UI.Droid.Resource.String.ApplicationName;
			global::Acr.UserDialogs.Resource.String.Hello = global::SevenDays.UI.Droid.Resource.String.Hello;
			global::Acr.UserDialogs.Resource.String.library_name = global::SevenDays.UI.Droid.Resource.String.library_name;
			global::Acr.UserDialogs.Resource.Styleable.ProgressWheel = global::SevenDays.UI.Droid.Resource.Styleable.ProgressWheel;
			global::Acr.UserDialogs.Resource.Styleable.ProgressWheel_ahBarColor = global::SevenDays.UI.Droid.Resource.Styleable.ProgressWheel_ahBarColor;
			global::Acr.UserDialogs.Resource.Styleable.ProgressWheel_ahBarLength = global::SevenDays.UI.Droid.Resource.Styleable.ProgressWheel_ahBarLength;
			global::Acr.UserDialogs.Resource.Styleable.ProgressWheel_ahBarWidth = global::SevenDays.UI.Droid.Resource.Styleable.ProgressWheel_ahBarWidth;
			global::Acr.UserDialogs.Resource.Styleable.ProgressWheel_ahCircleColor = global::SevenDays.UI.Droid.Resource.Styleable.ProgressWheel_ahCircleColor;
			global::Acr.UserDialogs.Resource.Styleable.ProgressWheel_ahDelayMillis = global::SevenDays.UI.Droid.Resource.Styleable.ProgressWheel_ahDelayMillis;
			global::Acr.UserDialogs.Resource.Styleable.ProgressWheel_ahRadius = global::SevenDays.UI.Droid.Resource.Styleable.ProgressWheel_ahRadius;
			global::Acr.UserDialogs.Resource.Styleable.ProgressWheel_ahRimColor = global::SevenDays.UI.Droid.Resource.Styleable.ProgressWheel_ahRimColor;
			global::Acr.UserDialogs.Resource.Styleable.ProgressWheel_ahRimWidth = global::SevenDays.UI.Droid.Resource.Styleable.ProgressWheel_ahRimWidth;
			global::Acr.UserDialogs.Resource.Styleable.ProgressWheel_ahSpinSpeed = global::SevenDays.UI.Droid.Resource.Styleable.ProgressWheel_ahSpinSpeed;
			global::Acr.UserDialogs.Resource.Styleable.ProgressWheel_ahText = global::SevenDays.UI.Droid.Resource.Styleable.ProgressWheel_ahText;
			global::Acr.UserDialogs.Resource.Styleable.ProgressWheel_ahTextColor = global::SevenDays.UI.Droid.Resource.Styleable.ProgressWheel_ahTextColor;
			global::Acr.UserDialogs.Resource.Styleable.ProgressWheel_ahTextSize = global::SevenDays.UI.Droid.Resource.Styleable.ProgressWheel_ahTextSize;
			global::PCLStorage.Resource.String.ApplicationName = global::SevenDays.UI.Droid.Resource.String.ApplicationName;
			global::PCLStorage.Resource.String.Hello = global::SevenDays.UI.Droid.Resource.String.Hello;
			global::Toasts.Forms.Plugin.Droid.Resource.Drawable.error = global::SevenDays.UI.Droid.Resource.Drawable.error;
			global::Toasts.Forms.Plugin.Droid.Resource.Drawable.info = global::SevenDays.UI.Droid.Resource.Drawable.info;
			global::Toasts.Forms.Plugin.Droid.Resource.Drawable.success = global::SevenDays.UI.Droid.Resource.Drawable.success;
			global::Toasts.Forms.Plugin.Droid.Resource.Drawable.warning = global::SevenDays.UI.Droid.Resource.Drawable.warning;
			global::Toasts.Forms.Plugin.Droid.Resource.Id.desc = global::SevenDays.UI.Droid.Resource.Id.desc;
			global::Toasts.Forms.Plugin.Droid.Resource.Id.image = global::SevenDays.UI.Droid.Resource.Id.image;
			global::Toasts.Forms.Plugin.Droid.Resource.Id.title = global::SevenDays.UI.Droid.Resource.Id.title;
			global::Toasts.Forms.Plugin.Droid.Resource.Layout.crouton = global::SevenDays.UI.Droid.Resource.Layout.crouton;
			global::Toasts.Forms.Plugin.Droid.Resource.String.ApplicationName = global::SevenDays.UI.Droid.Resource.String.ApplicationName;
			global::Toasts.Forms.Plugin.Droid.Resource.String.Hello = global::SevenDays.UI.Droid.Resource.String.Hello;
			global::Xamarin.Forms.Platform.Resource.String.ApplicationName = global::SevenDays.UI.Droid.Resource.String.ApplicationName;
			global::Xamarin.Forms.Platform.Resource.String.Hello = global::SevenDays.UI.Droid.Resource.String.Hello;
			global::Xamarin.InsightsCore.Resource.String.ApplicationName = global::SevenDays.UI.Droid.Resource.String.ApplicationName;
			global::Xamarin.InsightsCore.Resource.String.Hello = global::SevenDays.UI.Droid.Resource.String.Hello;
		}
		
		public partial class Attribute
		{
			
			static Attribute()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Attribute()
			{
			}
		}
		
		public partial class Drawable
		{
			
			// aapt resource value: 0x7f020000
			public const int error = 2130837504;
			
			// aapt resource value: 0x7f020001
			public const int icon = 2130837505;
			
			// aapt resource value: 0x7f020002
			public const int info = 2130837506;
			
			// aapt resource value: 0x7f020003
			public const int map = 2130837507;
			
			// aapt resource value: 0x7f020004
			public const int menu = 2130837508;
			
			// aapt resource value: 0x7f020005
			public const int people = 2130837509;
			
			// aapt resource value: 0x7f020006
			public const int settings = 2130837510;
			
			// aapt resource value: 0x7f020007
			public const int success = 2130837511;
			
			// aapt resource value: 0x7f020008
			public const int warning = 2130837512;
			
			static Drawable()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Drawable()
			{
			}
		}
		
		public partial class Id
		{
			
			// aapt resource value: 0x7f050002
			public const int desc = 2131034114;
			
			// aapt resource value: 0x7f050000
			public const int image = 2131034112;
			
			// aapt resource value: 0x7f050001
			public const int title = 2131034113;
			
			static Id()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Id()
			{
			}
		}
		
		public partial class Layout
		{
			
			// aapt resource value: 0x7f030000
			public const int crouton = 2130903040;
			
			static Layout()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Layout()
			{
			}
		}
		
		public partial class String
		{
			
			// aapt resource value: 0x7f040001
			public const int ApplicationName = 2130968577;
			
			// aapt resource value: 0x7f040000
			public const int Hello = 2130968576;
			
			static String()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private String()
			{
			}
		}
	}
}
#pragma warning restore 1591
